version: '3'

services:
  api:
    depends_on:
      - postgres
      - redis
    build:
      context: deploy/api
      dockerfile: Dockerfile
    tty: true
    ports:
      - "${SERVER_PORT}:3000"
    env_file:
      - .env
    # restart: always
    networks:
      - net

  postgres:
    build:
      context: deploy/postgres
      dockerfile: Dockerfile
    # restart: always
    tty: true
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    # restart: always
    networks:
      - net

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - net
    # restart: always

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8003:8080
    networks:
      - net

networks:
  net:
    driver: bridge